apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.2

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          ports:
            - containerPort: 3005
              protocol: TCP

          volumeMounts:
            - name: audiobookshelf-config-volume
              mountPath: /config
            - name: audiobookshelf-metadata-volume
              mountPath: /metadata
            - name: audiobookshelf-audiobooks-volume
              mountPath: /audiobooks

      restartPolicy: Always

      volumes:
        - name: audiobookshelf-config-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-metadata-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobookshelf-audiobooks-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
