apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.2

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          ports:
            - containerPort: 3005
              protocol: TCP

    restartPolicy:
      Always

      #     env:
      #       - name: PUID
      #         valueFrom:
      #           fieldRef:
      #             fieldPath: metadata.annotations['puid']
      #       - name: PGID
      #         valueFrom:
      #           fieldRef:
      #             fieldPath: metadata.annotations['pgid']
      #     volumeMounts:
      #       - name: config-volume
      #         mountPath: /config
      # volumes:
      #   - name: config-volume
      #     persistentVolumeClaim:
      #       claimName: audiobookshelf-config-pvc
