apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      securityContext:
        fsGroup: 1000 # nobody group ID
        runAsUser: 1000 # nobody user ID
        runAsGroup: 1000 # nobody group ID

      containers:
        - name: game
          image: erichodgins/third-person-camera:1.0.4
          ports:
            - containerPort: 80

          securityContext:
            allowPrivilegeEscalation: false

    #       securityContext:
    #         runAsUser: 1000
    #         runAsGroup: 1000
    #         runAsNonRoot: true
    #         allowPrivilegeEscalation: false
    #         readOnlyRootFilesystem: true

    # securityContext:
    #   fsGroup: 1000
