apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      # securityContext:
      #   fsGroup: 1000 # added app user
      #   runAsUser: 1000 # added app user
      #   runAsGroup: 1000 # added app user

      containers:
        - name: game
          image: erichodgins/third-person-camera:1.0.5
          ports:
            - containerPort: 80

          # securityContext:
          #   allowPrivilegeEscalation: false
