apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      # securityContext:
      #   fsGroup: 101 # nobody group ID
      #   runAsUser: 101 # nobody user ID
      #   runAsGroup: 101 # nobody group ID

      containers:
        - name: game
          image: erichodgins/third-person-camera:latest
          ports:
            - containerPort: 80

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

    securityContext:
      fsGroup: 1000
