apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yzQ1lXVkSKXCtyI0y8zc6c9jZsUT9e5DwF1rX+wVXTSLfhN5l52i2rYXUsKZG+NLu8fk7Ba2vnVQ0r4cj9jOTnY4QQKFiSskHDJdki4bKErLtQ/NiaT3QrnfRRgJc4M6yUBO3X8Yik4Rr1HjydgqTOriku0U1TiDF3+HL/sBhgf/PWFVQv6XIEZjais0EyrK9q9Rf142xL+CqEf9DlmUV/YscwDptOLZeG0Qr514T+/eyfosUu+Qrfg44or+JvHtXnntMgCjo+YHmMw1vMvK6PKS1h/kOZOukiiz05Z9EGE/WtH7UEm69HToSkE=,iv:s2dE+pT5Dygr8t3MxWHQufnNb5JCEAhW/8MErnmXfuo=,tag:EoflDKoFmYokKlOTlx40nw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1q52kwvrcxvey0rf3xxhdnzwnguslz4w3ck5pm7pel5kfdfcpvv7sg5fla5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bE84UDBRaHBNZ09sSm5Z
            d3BhNlJhcXZRRmIyam05bXl6enFxYklEYm1ZCkd5MUROVXovSk9GMkw0ZjRoZXFs
            RzkzWE5xK1lsSmpBcFFnZXJzRzhFZ2sKLS0tIEdZV3hRV0o1elp6c3lnRHMyN1J2
            QnNDQndDbFFTOUw3SlNlTDIzaXJWSzgKZ7Zapf0B/7YK+YFw4ni1FdWuZKyGmavd
            1W8NlkpfR7ntbGqZssZOR5JXSwtyVJjvP0xyT6NBcoKng8Ugi7zq3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T02:54:12Z"
    mac: ENC[AES256_GCM,data:sZQ8OCiBaSI9qxqhbkt/DHziUzQY5lLjq1ppXZ9xwbS70PCIew5q29OcFY6hYZra3vCf/cGu7nWw+TOzDFqKSHI444yT4worexvzKrPnpu0CbtMeDJC7jh9EwQ4TGD8Yz4hT78wJksyrHovHOxAWjrBZCJwlSqzvGaY2w+j7hM4=,iv:BB1e/mW15r0sWpcMiZRsXJxYJ1jQFxkUKh3iWGs/pj0=,tag:hKfroXh6J+4MfL2N/lTbAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
